### PR TITLE
make it compile with new alibuld

### PR DESCRIPTION
**Pull request by pbuehler**

### CODE REVIEW

**Comment by preghenella** [comment]
hi @pbuehler ,
thanks for the updates.
can you please specify why they are needed?

**Comment by pbuehler** [comment]
@preghenella these changes are needed to compile STARlight with a recent versiion of aliBuild.

**Comment by preghenella** [comment]
yes, this was clear from the title of the PR ;)
my question was to have more details of the reason of the failure.
given the build was apparently working till now something has changes in `aliBuild` and IMO the modification to make it build is possibly to be found in the `alidist` recipe responsible for the build.

**Comment by pbuehler** [comment]
I do not know which changes in the aliBuild system exactly make this update necessary. Without these modifications I get the following error message:

In file included from /home/pbuehler/alice/sw/SOURCES/STARlight/master/0/include/starlightparticle.h:38,
                 from /home/pbuehler/alice/sw/SOURCES/STARlight/master/0/src/starlightparticle.cpp:34:
/home/pbuehler/alice/sw/SOURCES/STARlight/master/0/include/lorentzvector.h: In copy constructor 'constexpr lorentzVector::lorentzVector(const lorentzVector&)':
/home/pbuehler/alice/sw/SOURCES/STARlight/master/0/include/lorentzvector.h:42:7: error: implicitly-declared 'constexpr vector3::vector3(const vector3&)' is deprecated [-Werror=deprecated-copy]
   42 | class lorentzVector
      |       ^~~~~~~~~~~~~
In file included from /home/pbuehler/alice/sw/SOURCES/STARlight/master/0/include/lorentzvector.h:38,
                 from /home/pbuehler/alice/sw/SOURCES/STARlight/master/0/include/starlightparticle.h:38,
                 from /home/pbuehler/alice/sw/SOURCES/STARlight/master/0/src/starlightparticle.cpp:34:
/home/pbuehler/alice/sw/SOURCES/STARlight/master/0/include/vector3.h:55:15: note: because 'vector3' has user-provided 'vector3& vector3::operator=(const vector3&)'
   55 |      vector3& operator =(const vector3& vec)
      |               ^~~~~~~~
In file included from /home/pbuehler/alice/sw/SOURCES/STARlight/master/0/src/starlightparticle.cpp:34:
/home/pbuehler/alice/sw/SOURCES/STARlight/master/0/include/starlightparticle.h: In member function 'lorentzVector starlightParticle::getVertex() const':
/home/pbuehler/alice/sw/SOURCES/STARlight/master/0/include/starlightparticle.h:75:48: note: synthesized method 'constexpr lorentzVector::lorentzVector(const lorentzVector&)' first required here
   75 |       lorentzVector getVertex() const { return _vertex; }
      |                                                ^~~~~~~
cc1plus: all warnings being treated as errors
gmake[2]: *** [CMakeFiles/Starlib.dir/build.make:132: CMakeFiles/Starlib.dir/src/starlightparticle.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/Starlib.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

**Comment by preghenella** [comment]
ok, thanks. let's merge and tag a new release.

**Pull request merged**
